[toolchain]
# anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "C1Hj34Yrhc2R4vnFbRtABeoRLozAnx9VhgpScg3hHuHp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://172.17.0.1:8890"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
